import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import { mkdtempSync, writeFileSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import { test } from "node:test";
const script = fileURLToPath(new URL("../../bin/loop-usage.py", import.meta.url));
test("whole-loop accounting includes reset sessions, deduplicates Claude blocks, counts Pi and separates preparation", t => {
  const dir = mkdtempSync(join(tmpdir(), "crate-usage-")); t.after(() => rmSync(dir, { recursive: true, force: true }));
  const claude = (id: string, timestamp: string, output: number) => ({ type: "assistant", timestamp, message: { id, usage: { input_tokens: 2, output_tokens: output, cache_read_input_tokens: 100, cache_creation_input_tokens: 10 } } });
  const pre = join(dir, "discarded.jsonl"), post = join(dir, "review.jsonl"), pi = join(dir, "pi.jsonl");
  writeFileSync(pre, JSON.stringify(claude("pre", "2026-09-14T10:01:00Z", 3)) + "\n");
  writeFileSync(post, [claude("review", "2026-09-14T10:06:00Z", 4), claude("review", "2026-09-14T10:06:01Z", 8)].map(r => JSON.stringify(r)).join("\n"));
  writeFileSync(pi, JSON.stringify({ type: "message", id: "p1", timestamp: "2026-09-14T10:02:00Z", message: { role: "assistant", usage: { input: 20, output: 5, cacheRead: 200, cacheWrite: 0 } } }));
  const manifest = { start: "2026-09-14T10:00:00Z", end: "2026-09-14T10:10:00Z", code_ready: "2026-09-14T10:05:00Z", idle_seats: ["coder", "tester", "designer"], sessions: [{ seat: "reviewer", provider: "claude", path: pre }, { seat: "reviewer", provider: "claude", path: post }, { seat: "orchestrator", provider: "pi", path: pi }] };
  const path = join(dir, "manifest.json");
  const run = () => { writeFileSync(path, JSON.stringify(manifest)); const r = spawnSync("python3", [script, path], { encoding: "utf8" }); return { code: r.status, report: JSON.parse(r.stdout) }; };
  let r = run(); assert.equal(r.code, 0); assert.equal(r.report.totals.model_requests, 3); assert.equal(r.report.totals.output_tokens, 16); assert.equal(r.report.totals.cache_read_tokens, 400);
  assert.equal(r.report.seats.reviewer.before_code_ready.model_requests, 1);
  manifest.sessions[2]!.provider = "claude"; r = run(); assert.equal(r.code, 1); assert.ok(r.report.errors.some((e: string) => e.includes("provider mismatch")));
  manifest.sessions[2]!.provider = "pi"; manifest.sessions[1]!.provider = "pi"; r = run(); assert.equal(r.code, 1);
  manifest.sessions[1]!.provider = "claude";
  const savedEnd = manifest.end, savedStart = manifest.start, savedReady = manifest.code_ready;
  manifest.start = "2026-09-15T10:00:00Z"; manifest.end = "2026-09-15T10:10:00Z"; manifest.code_ready = "2026-09-15T10:05:00Z";
  r = run(); assert.equal(r.code, 1); assert.ok(r.report.errors.some((e: string) => e.includes("no valid in-window usage")));
  manifest.start = savedStart; manifest.end = savedEnd; manifest.code_ready = savedReady;
  writeFileSync(pi, ""); r = run(); assert.equal(r.code, 1); assert.ok(r.report.errors.some((e: string) => e.includes("no recognized assistant")));
  manifest.sessions[0]!.path = join(dir, "missing"); r = run(); assert.equal(r.code, 1); assert.equal(r.report.status, "incomplete");
  manifest.sessions[0]!.path = pre; writeFileSync(pre, "{partial"); r = run(); assert.equal(r.code, 1);
  manifest.idle_seats = []; r = run(); assert.equal(r.code, 1); assert.ok(r.report.errors.some((e: string) => e.includes("not inventoried")));
});
